--Create Table Pessoa--
CREATE TABLE Pessoa(
	Id int IDENTITY(1,1) NOT NULL,
	Nome [nvarchar](100) NOT NULL,
	DataNascimento date NOT NULL,
	ValorRenda decimal(18, 0) NOT NULL,
	CPF nvarchar(11) NOT NULL,
 CONSTRAINT PK_Pessoa PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


--Create Table Tarefa--
CREATE TABLE Tarefa(
	Id int IDENTITY(1,1) NOT NULL,
	NomeTarefa nvarchar(50) NOT NULL,
	DataConclusao datetime NOT NULL,
	IdPessoa int NOT NULL,
 CONSTRAINT PK_Tarefa PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE Tarefa  WITH CHECK ADD  CONSTRAINT FK_Tarefa_Pessoa FOREIGN KEY(IdPessoa)
REFERENCES Pessoa (Id)
GO

ALTER TABLE Tarefa CHECK CONSTRAINT FK_Tarefa_Pessoa
GO




